### PR TITLE
Allow database user to be specified

### PR DESCRIPTION
**Pull request by gmfrasca**
- Allow user to change database username by setting JUPYTERHUB_DATABASE_USER
- Still default to 'jupyterhub' as standard username if not set
- ODH-425

### CODE REVIEW

**Comment by gmfrasca** [comment]
[Testing Instructions](https://github.com/opendatahub-io/jupyterhub-quickstart/files/6880968/dbuser-test-instructions.md)

**Review by anishasthana — APPROVED** [review]
Changes look good to me.
Deployed jupyterhub also functioned as expected.
:ship:

**Comment by vpavlin** [comment]
lgtm

**Comment by vpavlin** [comment]
@gmfrasca Since you are also fixing the templates, it would make sense to check the postgres deployments - the `jupyterhub` user is hardcoded there as well

**Comment by vpavlin** [comment]
lgtm

**Comment by VaishnaviHire** [comment]
lgtm

**Pull request merged**
